spring:
  profiles:
    active:  smart
hr:
  employeeRaisedPay:
    smart:
      limitHigh: 10
      limitMiddle: 5
      limitLow: 2.5
      percentHigh: 10
      percentMiddle: 5
      percentLow: 2